
//get  http://127.0.0.1:3000/api/v1/tours/fdfd

# post http://127.0.0.1:3000/api/v1/tours
# Content-Type: application/json

# {
#     "name": "Tour megahyper",
#     "duration": 1,
#     "maxGroupSize": 1,
#     "difficulty": "difficult",
#     "price": 1,
#     "summary": "Test tour",
#     "imageCover": "tour-3-cover.jpg",
#     "secretTour": true
# }

post http://127.0.0.1:3000/api/v1/users/signup
Content-Type: application/json

{
    "name": "jonas",
    "email": "elios@elios.com",
    "password": "1234",
    "passwordConfirm": "1234"
}